name: Test de facturacion
on: 
  push:
    branches: ["master"]
  pull_request: 
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        
      - name: Instalar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar código Java
        run: javac -cp ".:lib/*" -d out src/modelo/*.java test/tests/FacturacionTest.java
          
