name: Despliegue a Producción

on: 
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Compilar para producción
        run: javac -cp "lib/*" -d out $(find src test -name "*.java")

      - name: Ejecutar programa en Producción
        run: java -cp out src/vista/FrmLogin.java

        
