name: Java CI with Ant and MySQL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: db_usuario
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  # Cambia si usas otra

      - name: Wait for MySQL to be ready
        run: sleep 20

      - name: Install Ant
        run: sudo apt-get update && sudo apt-get install -y ant

      - name: Run Ant tests
        run: ant test
        env:
          DB_URL: jdbc:mysql://localhost:3306/testdb
          DB_USERNAME: testuser
          DB_PASSWORD: testpass
